
##创建项目
1-yarn-init:
	yarn init


##执行hardhat的安装
2-npx hardhat init:
	npx hardhat init


##这部署
3-npx hardhat compile:
	npx hardhat compile

##单测   comsole.log 可以打印 solidity 变量
4-npx hardhat test:
	npx hardhat test


5-npx hardhat test:
	npx hardhat test test/hello.js

6-npx hardhat test:
	npx hardhat test "test/1 The Basics/MyFirstContract.js"