



##编译
2-truffle-compile:
	truffle compile

## 切换Ganache 在 非开发模式下 ，执行 migrate（）

3-truffle-migrate:
	truffle migrate


4-truffle-test:
	truffle test

## You can also run each test individually by calling truffle test ./test/TestMetaCoin.sol and truffle test ./test/metacoin.js.

