
#创建空项目
1-truffle-init:
	truffle init

1-0-truffle-create:
	truffle create contract YourContractName

1-0-truffle-create-test:
	truffle create test YourTestName


##编译
2-truffle-compile:
	truffle compile


##这部署
3-truffle-migrate:
	truffle migrate

##测试
3-truffle-test:
	truffle test



java:
	sudo bash -x ./deploy-local-gary.sh
